version: '3.7'

services:

  db:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_DB=calistopia
      - POSTGRES_USER=calistopia
      - POSTGRES_PASSWORD=calistopia
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '8001:5432'
  web:
    build: .
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/calistopia
    ports:
      - "8000:8000"
    depends_on:
      - db